# Generated by Django 4.2.11 on 2024-03-28 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Workouts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_id', models.CharField(max_length=50, unique=True)),
                ('day', models.CharField(max_length=20)),
                ('workout_name', models.CharField(max_length=100)),
                ('exercises', models.TextField()),
            ],
        ),
    ]
