# Generated by Django 4.2.11 on 2024-08-14 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_customeraccounts_date_otheraccounts_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customeraccounts',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='otheraccounts',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
