# Generated by Django 4.2.11 on 2024-08-14 09:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_customeraccounts_date_alter_otheraccounts_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customeraccounts',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='otheraccounts',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
