# Generated by Django 4.2.11 on 2024-08-14 10:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_remove_customeraccounts_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customeraccounts',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='otheraccounts',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
