# Generated by Django 4.2.11 on 2024-08-14 10:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_customeraccounts_date_otheraccounts_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customeraccounts',
            name='date',
        ),
        migrations.RemoveField(
            model_name='otheraccounts',
            name='date',
        ),
    ]
