# Generated by Django 4.2.11 on 2024-04-06 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assistant', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='assistant',
            name='assitantID',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
