# Generated by Django 4.2.11 on 2024-04-06 20:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assistant', '0002_assistant_assitantid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='assistant',
            old_name='assitantID',
            new_name='assistantID',
        ),
    ]
