# Generated by Django 4.2.11 on 2024-04-07 00:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assistant', '0003_rename_assitantid_assistant_assistantid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='assistant',
            old_name='first_name',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='assistant',
            name='last_name',
        ),
    ]
