# Generated by Django 4.2.11 on 2024-03-27 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('customer_id', models.CharField(max_length=50, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('weight', models.DecimalField(decimal_places=2, max_digits=5)),
                ('height_inches', models.PositiveIntegerField()),
                ('height_feet', models.PositiveIntegerField()),
                ('fitness_goal', models.TextField()),
            ],
        ),
    ]
