# Generated by Django 4.2.11 on 2024-07-10 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='instructor_id',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
