# Generated by Django 4.2.11 on 2024-03-31 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Diet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_id', models.CharField(max_length=50)),
                ('break_fast', models.CharField(max_length=50)),
                ('lunch', models.CharField(max_length=50)),
                ('preworkout', models.CharField(max_length=50)),
                ('postworkout', models.CharField(max_length=50)),
                ('dinner', models.CharField(max_length=50)),
            ],
        ),
    ]
