# Generated by Django 4.2.11 on 2024-04-09 07:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0003_dailyreport_weeklyreport_yearlyreport_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='duefee',
            old_name='student_name',
            new_name='customer_name',
        ),
    ]
