# Generated by Django 4.2.11 on 2024-04-09 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0005_alter_duefee_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='profit',
            name='totalprofit',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
            preserve_default=False,
        ),
    ]
