# Generated by Django 4.2.11 on 2024-04-09 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0006_profit_totalprofit'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyreport',
            name='totalprofit',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='weeklyreport',
            name='totalprofit',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='yearlyreport',
            name='totalprofit',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
            preserve_default=False,
        ),
    ]
