# Generated by Django 4.2.11 on 2024-04-10 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0007_dailyreport_totalprofit_weeklyreport_totalprofit_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerFitnessReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=100)),
                ('weight', models.IntegerField()),
                ('bodyfat', models.CharField(max_length=100)),
                ('fitnessLevel', models.CharField(max_length=100)),
            ],
        ),
    ]
